apiVersion: v1
kind: ConfigMap
metadata:
  name: fluxpay-config
  namespace: fluxpay
  labels:
    app.kubernetes.io/part-of: fluxpay
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: fluxpay
  POSTGRES_USER: fluxpay

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: fluxpay
  RABBITMQ_VHOST: fluxpay
