apiVersion: v1
kind: Service
metadata:
  name: fluxpay-api
  namespace: fluxpay
  labels:
    app.kubernetes.io/name: fluxpay-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: fluxpay

spec:
  type: NodePort

  selector:
    app.kubernetes.io/name: fluxpay-api

  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
      protocol: TCP
