apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: fluxpay
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: fluxpay
spec:
  serviceName: postgres
  replicas: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: postgres

  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: fluxpay

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: postgres
          image: postgres:18.6-alpine3.23
          imagePullPolicy: IfNotPresent

          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: fluxpay-config
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: fluxpay-config
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fluxpay-secrets
                  key: POSTGRES_PASSWORD

          startupProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          app.kubernetes.io/name: postgres
          app.kubernetes.io/component: database
          app.kubernetes.io/part-of: fluxpay

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi
