apiVersion: 1

deleteDatasources:
  - name: Tempo
    orgId: 1

datasources:
  - name: Tempo
    uid: fluxpay-tempo
    orgId: 1
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false

    jsonData:
      httpMethod: GET
