apiVersion: v1
kind: Secret
metadata:
  name: fluxpay-secrets
  namespace: fluxpay
  labels:
    app.kubernetes.io/part-of: fluxpay
type: Opaque

stringData:
  POSTGRES_PASSWORD: change-me
  RABBITMQ_PASSWORD: change-me
